/**
 * 此文件由 Meoo Cloud 自动生成并管理。严禁手动修改、覆盖或重新创建；云服务初始化、关联或恢复时会重新生成此文件。业务代码只能导入和使用本文件导出的内容。
 *
 * This file is automatically generated and managed by Meoo Cloud.
 * DO NOT edit, overwrite, or recreate it manually. Only import and use its exports.
 */

import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

declare global {
  interface ImportMetaEnv {
    readonly VITE_SUPABASE_URL?: string;
    readonly VITE_SUPABASE_ANON_KEY?: string;
    readonly VITE_ONEDAY_APP_ID?: string;
    readonly VITE_SUPABASE_AUTH_STORAGE_KEY?: string;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

function optionalEnv(value: string | undefined): string {
  return (value ?? '').trim();
}

// 本地修改（原平台生成逻辑为必填）：脱离 Meoo 平台自托管时允许为空，
// 为空则不发送 OneDay-App-Id 头，对话改由 VITE_CHAT_API 直连自托管服务（见 src/services/seqoutChat.ts）。
export const projectUrlId = optionalEnv(import.meta.env.VITE_ONEDAY_APP_ID);
export const supabaseUrl = optionalEnv(import.meta.env.VITE_SUPABASE_URL);
export const supabaseAnonKey = optionalEnv(import.meta.env.VITE_SUPABASE_ANON_KEY);
const supabaseAuthStorageKey =
  import.meta.env.VITE_SUPABASE_AUTH_STORAGE_KEY;

export function getSupabaseUrl(): string {
  return supabaseUrl;
}

/** 完全自托管（未配置 Supabase）时为 true：应用降级为纯游客模式（localStorage 会话），登录/云同步/排行榜不可用 */
export const isOfflineMode = !supabaseUrl || !supabaseAnonKey;

/**
 * 无 Supabase 时的占位客户端：调用链上的任何方法都返回自身，await 结果为 { data: null, error: null }；
 * auth 固定未登录（业务层据此走游客分支），统计等 fire-and-forget 调用静默空转。
 */
function createOfflineClient(): SupabaseClient<Database> {
  const nullResult = Promise.resolve({ data: null, error: null });
  const self: unknown = new Proxy(
    function () {},
    {
      get(_t, prop) {
        if (prop === 'then' || prop === 'catch' || prop === 'finally') {
          return nullResult[prop].bind(nullResult);
        }
        if (prop === 'auth') return offlineAuth;
        return self;
      },
      apply() {
        return self;
      },
    },
  );
  const offlineAuth = {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
    signOut: () => nullResult,
  };
  return self as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> = isOfflineMode
  ? createOfflineClient()
  : createClient<Database>(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        ...(supabaseAuthStorageKey
          ? { storageKey: supabaseAuthStorageKey }
          : {}),
      },
      global: {
        headers: projectUrlId ? { 'OneDay-App-Id': projectUrlId } : {},
      },
    });
